language: php
sudo: false
php:
- 5.5
env:
  global:
  - secure: Hnmno610194Z/ZXESCE685pkyHip4GmgBKbBVZYm+zhGLW+bvEc8n6Ojfw1IteLVJahnCaZ0tgKqRebRlrhebtmWD4y+n5D80pHPZFaUHKo+ulBZ0ThxjcDfUDcXrPkgUPimP0/uwt34gy6PmJMk0tc9DmGpnJPqVIshMBCu5cc=
  - secure: m6KO5Y9+1kOks4u8Ko0isBMGYQDOYdqbWE+qfrz4/NDx17x8wqeGMN5/QiQCHgdSMRaRJuB0FDTzzQwkSg7Ea5f4UbJZgEy2224870A6jB+X7kW1CopwmdE0b4rD1nDj6BKvMr6bO7iBxmahUlego7SStJoEPlj452TQUN6KZ3Y=
install:
    - npm install jshint
before_script:
    - mkdir sources_plugin
    - cd sources_plugin
    - git clone git@github.com:laterpay/laterpay-wordpress-plugin.git
    - cd ../
    - mkdir sources_test
    - cd sources_test
    - git clone -b feature/selenium-tests git@github.com:laterpay/laterpay-wordpress-plugin.git
    - cd ../
    - rm -f sources_test/laterpay-wordpress-plugin/selenium-tests/tests/_data/laterpay.zip
    - cd sources_plugin/laterpay-wordpress-plugin/
    - zip -r9 ../../sources_test/laterpay-wordpress-plugin/selenium-tests/tests/_data/laterpay.zip laterpay/
    - cd ../../
script:
    - # JSHint
    - jshint laterpay/asset_sources/js
    - # Selenium
    - cd sources_test/laterpay-wordpress-plugin/selenium-tests/
    - php codecept.phar run --html --steps -g UI1 --env firefox_win
    - mkdir -p tests/_reports/firefox_win
    - mv -f tests/_output/* tests/_reports/firefox_win
    - php codecept.phar run --html --steps -g UI1 --env safari_mac
    - mkdir -p tests/_reports/safari_mac
    - mv -f tests/_output/* tests/_reports/safari_mac
notifications:
    slack: laterpay:KtlgyYUZft7naQWn3yjM6yCu
